### ISSUE TITLE
Error displaying a model with attributes

### ISSUE THREAD

**Issue by BenjaminWeisheit** [Moose2Model/Moose2Model#101]
Hi @RainerWinkler,

When I try to display a model (all data or restricted) with packages, classes and attributes. This causes an Exception in the Moose Panel (please find the mse file attached, I run it a fresh Moose image which I downloaded today):
<img width="762" alt="107111051-0b857c00-684d-11eb-90a1-cc4f058ab79c" src="https://user-images.githubusercontent.com/77887261/107738388-da062800-6d06-11eb-978d-f5578f2f29d7.png">

Displaying the model without attributes (only packages or only packages and classes) works. 

Best regards,
Ben

**Comment by RainerWinkler** [comment]
Hi @BenjaminWeisheit,
you apparently used the stable version. Which is the proper way to do it. My impression is, that it is better to use the version which is specificied as development.
I propose you use the version which is named development and which I am currently using.
I will update the stable version, as it is probably outdated.
Can you please test, that the development version works for you?
Kind regards,
Rainer
PS:
You can still use this link to get the old version. The reason is, that Smalltalkhub will now be replaced with ss3.gemstone:
Metacello new
    smalltalkhubUser: 'RainerWinkler' project: 'RW-Moose-Diagram';
    configuration: 'Moose2Model';
    version: #stable;
    get;
    load.

**Comment by RainerWinkler** [comment]
Hi @BenjaminWeisheit ,
I removed the link to the zip file in your description, as it is not needed anymore here.
Kind regards,
Rainer

**Comment by BenjaminWeisheit** [comment]
Hi @RainerWinkler,

the development version works. I can now display attributes,too. Thanks for the advice.

Best regards,
Ben
